[workspace.package]
version = "0.7.4"
edition = "2021"
authors = [
    "Databend Authors <opensource@datafuselabs.com>",
    "Anthony Dodd <Dodd.AnthonyJosiah@gmail.com>"
]
categories = ["algorithms", "asynchronous", "data-structures"]
description = "Advanced Raft consensus"
documentation = "https://docs.rs/openraft"
homepage = "https://github.com/datafuselabs/openraft"
keywords = ["raft", "consensus"]
license = "MIT/Apache-2.0"
repository = "https://github.com/datafuselabs/openraft"

[workspace]
members = [
    "openraft",
    "memstore",
    "rocksstore",
]
