[package]
name = "openraft"
version = "0.7.3"
edition = "2021"
authors = [
    "Databend Authors <opensource@datafuselabs.com>",
    "Anthony Dodd <Dodd.AnthonyJosiah@gmail.com>"
]
categories = ["algorithms", "asynchronous", "data-structures"]
description = "Advanced Raft consensus"
documentation = "https://docs.rs/openraft"
homepage = "https://github.com/datafuselabs/openraft"
keywords = ["raft", "consensus"]
license = "MIT/Apache-2.0"
repository = "https://github.com/datafuselabs/openraft"
readme = "../README.md"

[dependencies]
anyerror = { version = "0.1.7", features = ["anyhow"]}
anyhow = "1.0.63"
async-trait = "0.1.36"
byte-unit = "4.0.12"
bytes = "1.0"
clap = { version = "3.0.7", features = ["derive", "env"] }
derive_more = { version="0.99.9" }
futures = "0.3"
maplit = "1.0.2"
rand = "0.8"
serde = { version="1", features=["derive"] }
thiserror = "1.0.33"
tokio = { version="1.8", default-features=false, features=["fs", "io-util", "macros", "rt", "rt-multi-thread", "sync", "time"] }
tracing = "0.1.29"
tracing-futures = "0.2.4"

[dev-dependencies]
lazy_static = "1.4.0"
openraft-memstore = { path="../memstore" }
pretty_assertions = "1.0.0"
tracing-appender = "0.2.0"
tracing-subscriber = { version = "0.3.3",  features=["env-filter"] }



[features]
docinclude = [] # Used only for activating `doc(include="...")` on nightly.

# Enable backtrace when generating an error.
# Stable rust does not support backtrace.
bt  = ["anyerror/backtrace", "anyhow/backtrace"]

[package.metadata.docs.rs]
features = ["docinclude"] # Activate `docinclude` during docs.rs build.
