name: Unit test coverage
on:
  push:
    branches:
      - "release-*"
      - "main"

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: llvm-tools-preview


      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov


      - name: Install cargo-expand
        run: cargo install cargo-expand


      - name: Generate coverage report
        # To test with all features:
        # run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
        run: cargo llvm-cov --workspace --lcov --output-path lcov.info
        env:
          RUST_TEST_THREADS: 2


      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: lcov.info
